/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

/**
 *
 * @author Liz
 */
public class ContactanosDoc extends javax.swing.JFrame {

    /**
     * Creates new form ContactanosDoc
     */
    public ContactanosDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentral = new javax.swing.JPanel();
        lblCorreoDoc = new javax.swing.JLabel();
        lblFacebookDoc = new javax.swing.JLabel();
        lblWhatsAppDoc = new javax.swing.JLabel();
        lblInstagramDoc = new javax.swing.JLabel();
        lblYoutubeDoc = new javax.swing.JLabel();
        lblTikTokDoc = new javax.swing.JLabel();
        pnlColor = new javax.swing.JPanel();
        lblRegreso = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCentral.setBackground(new java.awt.Color(13, 143, 131));

        lblCorreoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/threads.png"))); // NOI18N
        lblCorreoDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCorreoDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCorreoDocMouseClicked(evt);
            }
        });

        lblFacebookDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fb.png"))); // NOI18N
        lblFacebookDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFacebookDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacebookDocMouseClicked(evt);
            }
        });

        lblWhatsAppDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wsp.png"))); // NOI18N
        lblWhatsAppDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWhatsAppDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhatsAppDocMouseClicked(evt);
            }
        });

        lblInstagramDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ig.png"))); // NOI18N
        lblInstagramDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInstagramDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstagramDocMouseClicked(evt);
            }
        });

        lblYoutubeDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yt.png"))); // NOI18N
        lblYoutubeDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblYoutubeDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYoutubeDocMouseClicked(evt);
            }
        });

        lblTikTokDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiktok.png"))); // NOI18N
        lblTikTokDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTikTokDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTikTokDocMouseClicked(evt);
            }
        });

        pnlColor.setBackground(new java.awt.Color(255, 255, 255));
        pnlColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DireccionDoc.png"))); // NOI18N
        lblRegreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresoMouseClicked(evt);
            }
        });
        pnlColor.add(lblRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 50));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ContáctanosDoc.png"))); // NOI18N
        pnlColor.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, 50));

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblFacebookDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblWhatsAppDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInstagramDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblYoutubeDoc))
                    .addComponent(lblTikTokDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblCorreoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createSequentialGroup()
                .addComponent(pnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblFacebookDoc)
                .addGap(10, 10, 10)
                .addComponent(lblWhatsAppDoc)
                .addGap(10, 10, 10)
                .addComponent(lblInstagramDoc)
                .addGap(10, 10, 10)
                .addComponent(lblYoutubeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTikTokDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblCorreoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCorreoDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorreoDocMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI
                ("https://www.instagram.com/mediplus184/"));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblCorreoDocMouseClicked

    private void lblFacebookDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacebookDocMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI
                ("https://www.facebook.com/people/MediPlus/61553778142795/?sk=followers&locale=es_LA"));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblFacebookDocMouseClicked

    private void lblWhatsAppDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhatsAppDocMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI
                ("https://chat.whatsapp.com/KEv303KvG1o1GFPiAubTmk"));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblWhatsAppDocMouseClicked

    private void lblInstagramDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstagramDocMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI
                ("https://www.instagram.com/mediplus184/"));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblInstagramDocMouseClicked

    private void lblYoutubeDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYoutubeDocMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI
                ("https://www.youtube.com/channel/UCmZ2akKrpi-uMDAv2xLMABw"));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblYoutubeDocMouseClicked

    private void lblTikTokDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTikTokDocMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI
                ("https://www.tiktok.com/@medi_plus18"));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblTikTokDocMouseClicked

    private void lblRegresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresoMouseClicked
        MenuDoctor pantalla = new MenuDoctor();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRegresoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactanosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactanosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactanosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactanosDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactanosDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCorreoDoc;
    private javax.swing.JLabel lblFacebookDoc;
    private javax.swing.JLabel lblInstagramDoc;
    private javax.swing.JLabel lblRegreso;
    private javax.swing.JLabel lblTikTokDoc;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblWhatsAppDoc;
    private javax.swing.JLabel lblYoutubeDoc;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlColor;
    // End of variables declaration//GEN-END:variables
}
