/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import entidades.Usuario;

/**
 *
 * @author jaime
 */
public class MenuUsuario extends javax.swing.JFrame {

    private Usuario usuarioAutenticado;
    
    public MenuUsuario() {
        initComponents();
    }
    
     public void setUsuarioAutenticado(Usuario usuario) {
        this.usuarioAutenticado = usuario;
        actualizarNombreUsuario();
    }

      private void actualizarNombreUsuario() {
        if (usuarioAutenticado != null) {
            String nombreUsuario = usuarioAutenticado.getNombre();
            String apellidosUsuario = usuarioAutenticado.getApellidos();
            jMenuUsuario.setText("Usuario: " + nombreUsuario + " " + apellidosUsuario);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentral = new javax.swing.JPanel();
        lblInfoLabPac = new javax.swing.JLabel();
        lblListaCitasPac = new javax.swing.JLabel();
        lblAgendarCitaPac = new javax.swing.JLabel();
        lblBuscarDocPac = new javax.swing.JLabel();
        lblSobreNosotrosPac = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblContactanosPac = new javax.swing.JLabel();
        mbMenuPrincipal = new javax.swing.JMenuBar();
        mbMenuPrincipal1 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuUsuario = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        btnMenuPac = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btnEditarPac = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnVerCitaPac = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnContactanosPac = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btnSobreNosotrosPac = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCentral.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoLabPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VerResultados.png"))); // NOI18N
        pnlCentral.add(lblInfoLabPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 100, 90));

        lblListaCitasPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ListaDeCitas.png"))); // NOI18N
        pnlCentral.add(lblListaCitasPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 90));

        lblAgendarCitaPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgendarCita.png"))); // NOI18N
        lblAgendarCitaPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendarCitaPacMouseClicked(evt);
            }
        });
        pnlCentral.add(lblAgendarCitaPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, 90));

        lblBuscarDocPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BuscarDoctor.png"))); // NOI18N
        lblBuscarDocPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarDocPacMouseClicked(evt);
            }
        });
        pnlCentral.add(lblBuscarDocPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 90));

        lblSobreNosotrosPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SobreNosotros.png"))); // NOI18N
        lblSobreNosotrosPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSobreNosotrosPacMouseClicked(evt);
            }
        });
        pnlCentral.add(lblSobreNosotrosPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 90));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagenPacienteDoctor.png"))); // NOI18N
        pnlCentral.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 180));

        lblContactanosPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contactanos.png"))); // NOI18N
        lblContactanosPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactanosPacMouseClicked(evt);
            }
        });
        pnlCentral.add(lblContactanosPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 100, 90));

        getContentPane().add(pnlCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 520));

        mbMenuPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mbMenuPrincipal.setDoubleBuffered(true);
        mbMenuPrincipal.setFocusable(false);
        mbMenuPrincipal.setOpaque(true);
        mbMenuPrincipal.setPreferredSize(new java.awt.Dimension(70, 65));
        mbMenuPrincipal.setRequestFocusEnabled(false);

        mbMenuPrincipal1.setBorder(null);
        mbMenuPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMenu.png"))); // NOI18N
        mbMenuPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mbMenuPrincipal1.setPreferredSize(new java.awt.Dimension(65, 65));
        mbMenuPrincipal1.add(jSeparator6);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Perfil.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");
        jMenuUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuUsuario.setPreferredSize(new java.awt.Dimension(300, 85));
        mbMenuPrincipal1.add(jMenuUsuario);
        mbMenuPrincipal1.add(jSeparator7);

        btnMenuPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mnu.png"))); // NOI18N
        btnMenuPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuPac.setPreferredSize(new java.awt.Dimension(160, 50));
        btnMenuPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuPacMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnMenuPac);
        mbMenuPrincipal1.add(jSeparator2);

        btnEditarPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edtar.png"))); // NOI18N
        btnEditarPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPac.setPreferredSize(new java.awt.Dimension(160, 50));
        btnEditarPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPacMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnEditarPac);
        mbMenuPrincipal1.add(jSeparator1);

        btnVerCitaPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VerCita.png"))); // NOI18N
        btnVerCitaPac.setPreferredSize(new java.awt.Dimension(191, 50));
        btnVerCitaPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerCitaPacMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnVerCitaPac);
        mbMenuPrincipal1.add(jSeparator3);

        btnContactanosPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contactanos (2).png"))); // NOI18N
        btnContactanosPac.setPreferredSize(new java.awt.Dimension(230, 50));
        btnContactanosPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactanosPacMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnContactanosPac);
        mbMenuPrincipal1.add(jSeparator5);

        btnSobreNosotrosPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SobreNosotros2.png"))); // NOI18N
        btnSobreNosotrosPac.setPreferredSize(new java.awt.Dimension(202, 50));
        btnSobreNosotrosPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreNosotrosPacMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnSobreNosotrosPac);
        mbMenuPrincipal1.add(jSeparator4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarSession.png"))); // NOI18N
        jMenuItem6.setPreferredSize(new java.awt.Dimension(202, 50));
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(jMenuItem6);

        mbMenuPrincipal.add(mbMenuPrincipal1);

        jMenu1.setBackground(new java.awt.Color(242, 242, 242));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuLogo.png"))); // NOI18N
        jMenu1.setBorderPainted(false);
        jMenu1.setFocusable(false);
        jMenu1.setPreferredSize(new java.awt.Dimension(65, 65));
        jMenu1.setRequestFocusEnabled(false);
        jMenu1.setRolloverEnabled(false);
        jMenu1.setVerifyInputWhenFocusTarget(false);
        mbMenuPrincipal.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(242, 242, 242));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuLogoo.png"))); // NOI18N
        jMenu2.setMinimumSize(new java.awt.Dimension(200, 200));
        jMenu2.setPreferredSize(new java.awt.Dimension(300, 200));
        mbMenuPrincipal.add(jMenu2);

        setJMenuBar(mbMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContactanosPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactanosPacMouseClicked
        //Probando
        ContactanosUsuario pantalla = new ContactanosUsuario();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblContactanosPacMouseClicked

    private void lblAgendarCitaPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendarCitaPacMouseClicked
        AgendarCita pantalla = new AgendarCita();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgendarCitaPacMouseClicked

    private void lblBuscarDocPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarDocPacMouseClicked
        ListaDeDoctores1 pantalla = new ListaDeDoctores1();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblBuscarDocPacMouseClicked

    private void lblSobreNosotrosPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSobreNosotrosPacMouseClicked
        SobreNosotros pantalla = new SobreNosotros();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSobreNosotrosPacMouseClicked

    private void btnContactanosPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactanosPacMouseClicked
        ContactanosUsuario pantalla = new ContactanosUsuario();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnContactanosPacMouseClicked

    private void btnSobreNosotrosPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreNosotrosPacMouseClicked
        SobreNosotros pantalla = new SobreNosotros();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobreNosotrosPacMouseClicked

    private void jMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseClicked
        LoginUsuario pantalla = new LoginUsuario();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6MouseClicked

    private void btnVerCitaPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerCitaPacMouseClicked
        ListaCitas pantalla = new ListaCitas();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerCitaPacMouseClicked

    private void btnMenuPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPacMouseClicked
        MenuUsuario pantalla = new MenuUsuario();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuPacMouseClicked

    private void btnEditarPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPacMouseClicked
        EditarPerfil pantalla = new EditarPerfil();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditarPacMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnContactanosPac;
    private javax.swing.JMenuItem btnEditarPac;
    private javax.swing.JMenuItem btnMenuPac;
    private javax.swing.JMenuItem btnSobreNosotrosPac;
    private javax.swing.JMenuItem btnVerCitaPac;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lblAgendarCitaPac;
    private javax.swing.JLabel lblBuscarDocPac;
    private javax.swing.JLabel lblContactanosPac;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInfoLabPac;
    private javax.swing.JLabel lblListaCitasPac;
    private javax.swing.JLabel lblSobreNosotrosPac;
    private javax.swing.JMenuBar mbMenuPrincipal;
    private javax.swing.JMenu mbMenuPrincipal1;
    private javax.swing.JPanel pnlCentral;
    // End of variables declaration//GEN-END:variables
}
