/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import entidades.Usuario;

/**
 *
 * @author jaime
 */
public class MenuDoctor extends javax.swing.JFrame {

    private Usuario medicoAutenticado;
    
    public MenuDoctor() {
        initComponents();
    }
    
     public void setUsuarioAutenticado(Usuario usuario) {
        this.medicoAutenticado = usuario;
        actualizarNombreUsuario();
    }

      private void actualizarNombreUsuario() {
        if (medicoAutenticado != null) {
            String nombreUsuario = medicoAutenticado.getNombre();
            String apellidosUsuario = medicoAutenticado.getApellidos();
            jMenuUsuario.setText("Doctor: " + nombreUsuario + " " + apellidosUsuario);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentral = new javax.swing.JPanel();
        lblInfoLabDoc = new javax.swing.JLabel();
        lblListaCitasDoc = new javax.swing.JLabel();
        lblRevisarCitaDoc = new javax.swing.JLabel();
        lblBuscarDoc = new javax.swing.JLabel();
        lblSobreNosotrosDoc = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblContactosDoc = new javax.swing.JLabel();
        mbMenuPrincipal = new javax.swing.JMenuBar();
        mbMenuPrincipal1 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuUsuario = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        btnMenuDoc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnListaCitasDoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnContactanosDoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btnSobreNosotrosDoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnCerrarSesionDoc = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCentral.setBackground(new java.awt.Color(13, 143, 131));
        pnlCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoLabDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VerInfoooooooooo.png"))); // NOI18N
        lblInfoLabDoc.setPreferredSize(new java.awt.Dimension(90, 90));
        lblInfoLabDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInfoLabDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblInfoLabDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 100, 90));

        lblListaCitasDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ListaDeCitas.png"))); // NOI18N
        lblListaCitasDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListaCitasDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblListaCitasDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 100, 90));

        lblRevisarCitaDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RevisarCita.png"))); // NOI18N
        lblRevisarCitaDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRevisarCitaDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRevisarCitaDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblRevisarCitaDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 100, 90));

        lblBuscarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BuscarPacientes.png"))); // NOI18N
        lblBuscarDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblBuscarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, 90));

        lblSobreNosotrosDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SobreNosotros.png"))); // NOI18N
        lblSobreNosotrosDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSobreNosotrosDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSobreNosotrosDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblSobreNosotrosDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 100, 90));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagenPacienteDoctor.png"))); // NOI18N
        pnlCentral.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 180));

        lblContactosDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contactanos.png"))); // NOI18N
        lblContactosDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContactosDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactosDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblContactosDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 100, 90));

        getContentPane().add(pnlCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 760));

        mbMenuPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mbMenuPrincipal.setFocusable(false);
        mbMenuPrincipal.setOpaque(true);
        mbMenuPrincipal.setPreferredSize(new java.awt.Dimension(70, 65));
        mbMenuPrincipal.setRequestFocusEnabled(false);

        mbMenuPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMenu.png"))); // NOI18N
        mbMenuPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mbMenuPrincipal1.setPreferredSize(new java.awt.Dimension(65, 65));
        mbMenuPrincipal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbMenuPrincipal1MouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(jSeparator6);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Perfil.png"))); // NOI18N
        jMenuUsuario.setText("¡Bienvenido!");
        jMenuUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuUsuario.setPreferredSize(new java.awt.Dimension(300, 85));
        mbMenuPrincipal1.add(jMenuUsuario);
        mbMenuPrincipal1.add(jSeparator7);

        btnMenuDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mnu.png"))); // NOI18N
        btnMenuDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuDoc.setPreferredSize(new java.awt.Dimension(160, 50));
        mbMenuPrincipal1.add(btnMenuDoc);
        mbMenuPrincipal1.add(jSeparator1);

        btnListaCitasDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VerCita.png"))); // NOI18N
        btnListaCitasDoc.setPreferredSize(new java.awt.Dimension(191, 50));
        btnListaCitasDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaCitasDocMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnListaCitasDoc);
        mbMenuPrincipal1.add(jSeparator3);

        btnContactanosDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contactanos (2).png"))); // NOI18N
        btnContactanosDoc.setPreferredSize(new java.awt.Dimension(230, 50));
        btnContactanosDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactanosDocMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnContactanosDoc);
        mbMenuPrincipal1.add(jSeparator5);

        btnSobreNosotrosDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SobreNosotros2.png"))); // NOI18N
        btnSobreNosotrosDoc.setPreferredSize(new java.awt.Dimension(202, 50));
        btnSobreNosotrosDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreNosotrosDocMouseClicked(evt);
            }
        });
        mbMenuPrincipal1.add(btnSobreNosotrosDoc);
        mbMenuPrincipal1.add(jSeparator4);

        btnCerrarSesionDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarSession.png"))); // NOI18N
        btnCerrarSesionDoc.setPreferredSize(new java.awt.Dimension(202, 50));
        btnCerrarSesionDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionDocActionPerformed(evt);
            }
        });
        mbMenuPrincipal1.add(btnCerrarSesionDoc);

        mbMenuPrincipal.add(mbMenuPrincipal1);

        jMenu1.setBackground(new java.awt.Color(242, 242, 242));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuLogo.png"))); // NOI18N
        jMenu1.setBorderPainted(false);
        jMenu1.setFocusable(false);
        jMenu1.setPreferredSize(new java.awt.Dimension(65, 65));
        jMenu1.setRequestFocusEnabled(false);
        jMenu1.setRolloverEnabled(false);
        jMenu1.setVerifyInputWhenFocusTarget(false);
        mbMenuPrincipal.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(242, 242, 242));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuLogoo.png"))); // NOI18N
        jMenu2.setMinimumSize(new java.awt.Dimension(200, 200));
        jMenu2.setPreferredSize(new java.awt.Dimension(300, 200));
        mbMenuPrincipal.add(jMenu2);

        setJMenuBar(mbMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContactosDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactosDocMouseClicked
        ContactanosUsuario pantalla = new ContactanosUsuario();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblContactosDocMouseClicked

    private void lblRevisarCitaDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRevisarCitaDocMouseClicked
        RevisarCita pantalla = new RevisarCita();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRevisarCitaDocMouseClicked

    private void lblSobreNosotrosDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSobreNosotrosDocMouseClicked
        SobreNosotros pantalla = new SobreNosotros();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSobreNosotrosDocMouseClicked

    private void lblInfoLabDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInfoLabDocMouseClicked
        EnviarInformeLab pantalla = new EnviarInformeLab();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblInfoLabDocMouseClicked

    private void lblBuscarDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarDocMouseClicked
        BuscarPaciente pantalla = new BuscarPaciente();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblBuscarDocMouseClicked

    private void lblListaCitasDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaCitasDocMouseClicked
        ListaPacientes pantalla = new ListaPacientes();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblListaCitasDocMouseClicked

    private void btnContactanosDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactanosDocMouseClicked
        ContactanosDoc pantalla = new ContactanosDoc();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnContactanosDocMouseClicked

    private void btnSobreNosotrosDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreNosotrosDocMouseClicked
        SobreNosotrosDoc pantalla = new SobreNosotrosDoc();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobreNosotrosDocMouseClicked

    private void btnListaCitasDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaCitasDocMouseClicked
        ListaCitas pantalla = new ListaCitas();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListaCitasDocMouseClicked

    private void mbMenuPrincipal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbMenuPrincipal1MouseClicked
       
    }//GEN-LAST:event_mbMenuPrincipal1MouseClicked

    private void btnCerrarSesionDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionDocActionPerformed
        LoginDoctor pantalla = new LoginDoctor();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCerrarSesionDoc;
    private javax.swing.JMenuItem btnContactanosDoc;
    private javax.swing.JMenuItem btnListaCitasDoc;
    private javax.swing.JMenuItem btnMenuDoc;
    private javax.swing.JMenuItem btnSobreNosotrosDoc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lblBuscarDoc;
    private javax.swing.JLabel lblContactosDoc;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInfoLabDoc;
    private javax.swing.JLabel lblListaCitasDoc;
    private javax.swing.JLabel lblRevisarCitaDoc;
    private javax.swing.JLabel lblSobreNosotrosDoc;
    private javax.swing.JMenuBar mbMenuPrincipal;
    private javax.swing.JMenu mbMenuPrincipal1;
    private javax.swing.JPanel pnlCentral;
    // End of variables declaration//GEN-END:variables
}
