/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import entidades.Usuario;

/**
 *
 * @author jaime
 */
public class MenuUsuario extends javax.swing.JFrame {

    private Usuario usuarioAutenticado;
    
    public MenuUsuario() {
        initComponents();
    }
    
     public void setUsuarioAutenticado(Usuario usuario) {
        this.usuarioAutenticado = usuario;
        actualizarNombreUsuario();
    }

      private void actualizarNombreUsuario() {
        if (usuarioAutenticado != null) {
            String nombreUsuario = usuarioAutenticado.getNombre();
            String apellidosUsuario = usuarioAutenticado.getApellidos();
            jMenuUsuario.setText("Usuario: " + nombreUsuario + " " + apellidosUsuario);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentral = new javax.swing.JPanel();
        lblInfoLab = new javax.swing.JLabel();
        lblListaCitas = new javax.swing.JLabel();
        lblAgendarCita = new javax.swing.JLabel();
        lblBuscarDoc = new javax.swing.JLabel();
        lblSobreNosotros = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblContactos = new javax.swing.JLabel();
        mbMenuPrincipal = new javax.swing.JMenuBar();
        mbMenuPrincipal1 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuUsuario = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCentral.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VerResultados.png"))); // NOI18N
        pnlCentral.add(lblInfoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 100, 90));

        lblListaCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ListaDeCitas.png"))); // NOI18N
        pnlCentral.add(lblListaCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 90));

        lblAgendarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgendarCita.png"))); // NOI18N
        lblAgendarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendarCitaMouseClicked(evt);
            }
        });
        pnlCentral.add(lblAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 100, 90));

        lblBuscarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BuscarDoctor.png"))); // NOI18N
        lblBuscarDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarDocMouseClicked(evt);
            }
        });
        pnlCentral.add(lblBuscarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 90));

        lblSobreNosotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SobreNosotros.png"))); // NOI18N
        lblSobreNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSobreNosotrosMouseClicked(evt);
            }
        });
        pnlCentral.add(lblSobreNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 90));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagenPacienteDoctor.png"))); // NOI18N
        pnlCentral.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 180));

        lblContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contactanos.png"))); // NOI18N
        lblContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactosMouseClicked(evt);
            }
        });
        pnlCentral.add(lblContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 100, 90));

        getContentPane().add(pnlCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 760));

        mbMenuPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mbMenuPrincipal.setFocusable(false);
        mbMenuPrincipal.setOpaque(true);
        mbMenuPrincipal.setPreferredSize(new java.awt.Dimension(70, 65));
        mbMenuPrincipal.setRequestFocusEnabled(false);

        mbMenuPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMenu.png"))); // NOI18N
        mbMenuPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mbMenuPrincipal1.setPreferredSize(new java.awt.Dimension(65, 65));
        mbMenuPrincipal1.add(jSeparator6);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Perfil.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");
        jMenuUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuUsuario.setPreferredSize(new java.awt.Dimension(300, 85));
        mbMenuPrincipal1.add(jMenuUsuario);
        mbMenuPrincipal1.add(jSeparator7);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mnu.png"))); // NOI18N
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.setPreferredSize(new java.awt.Dimension(160, 50));
        mbMenuPrincipal1.add(jMenuItem1);
        mbMenuPrincipal1.add(jSeparator2);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edtar.png"))); // NOI18N
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.setPreferredSize(new java.awt.Dimension(160, 50));
        mbMenuPrincipal1.add(jMenuItem2);
        mbMenuPrincipal1.add(jSeparator1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VerCita.png"))); // NOI18N
        jMenuItem3.setPreferredSize(new java.awt.Dimension(191, 50));
        mbMenuPrincipal1.add(jMenuItem3);
        mbMenuPrincipal1.add(jSeparator3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Contactanos (2).png"))); // NOI18N
        jMenuItem4.setPreferredSize(new java.awt.Dimension(230, 50));
        mbMenuPrincipal1.add(jMenuItem4);
        mbMenuPrincipal1.add(jSeparator5);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SobreNosotros2.png"))); // NOI18N
        jMenuItem5.setPreferredSize(new java.awt.Dimension(202, 50));
        mbMenuPrincipal1.add(jMenuItem5);
        mbMenuPrincipal1.add(jSeparator4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CerrarSession.png"))); // NOI18N
        jMenuItem6.setPreferredSize(new java.awt.Dimension(202, 50));
        mbMenuPrincipal1.add(jMenuItem6);

        mbMenuPrincipal.add(mbMenuPrincipal1);

        jMenu1.setBackground(new java.awt.Color(242, 242, 242));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuLogo.png"))); // NOI18N
        jMenu1.setBorderPainted(false);
        jMenu1.setFocusable(false);
        jMenu1.setPreferredSize(new java.awt.Dimension(65, 65));
        jMenu1.setRequestFocusEnabled(false);
        jMenu1.setRolloverEnabled(false);
        jMenu1.setVerifyInputWhenFocusTarget(false);
        mbMenuPrincipal.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(242, 242, 242));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuLogoo.png"))); // NOI18N
        jMenu2.setMinimumSize(new java.awt.Dimension(200, 200));
        jMenu2.setPreferredSize(new java.awt.Dimension(300, 200));
        mbMenuPrincipal.add(jMenu2);

        setJMenuBar(mbMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactosMouseClicked
        //Probando
        ContactanosUsuario pantalla = new ContactanosUsuario();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblContactosMouseClicked

    private void lblAgendarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendarCitaMouseClicked
        AgendarCita pantalla = new AgendarCita();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgendarCitaMouseClicked

    private void lblBuscarDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarDocMouseClicked
        ListaDeDoctores1 pantalla = new ListaDeDoctores1();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblBuscarDocMouseClicked

    private void lblSobreNosotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSobreNosotrosMouseClicked
        SobreNosotros pantalla = new SobreNosotros();
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSobreNosotrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lblAgendarCita;
    private javax.swing.JLabel lblBuscarDoc;
    private javax.swing.JLabel lblContactos;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInfoLab;
    private javax.swing.JLabel lblListaCitas;
    private javax.swing.JLabel lblSobreNosotros;
    private javax.swing.JMenuBar mbMenuPrincipal;
    private javax.swing.JMenu mbMenuPrincipal1;
    private javax.swing.JPanel pnlCentral;
    // End of variables declaration//GEN-END:variables
}
